# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyjsoneditor.ui'
#
# Created: Wed Sep 15 00:11:47 2010
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 712)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window_icon.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_0 = QtGui.QHBoxLayout()
        self.horizontalLayout_0.setObjectName("horizontalLayout_0")
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_0.addWidget(self.pushButton_2)
        self.lineEdit_0 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_0.setObjectName("lineEdit_0")
        self.horizontalLayout_0.addWidget(self.lineEdit_0)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_0.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_0)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout = QtGui.QGridLayout(self.tab_1)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.tab_1)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.treeWidget_1 = QtGui.QTreeWidget(self.splitter)
        self.treeWidget_1.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidget_1.setObjectName("treeWidget_1")
        self.textBrowser_1 = QtGui.QTextBrowser(self.splitter)
        self.textBrowser_1.setUndoRedoEnabled(True)
        self.textBrowser_1.setReadOnly(False)
        self.textBrowser_1.setAcceptRichText(False)
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.horizontalLayout_1 = QtGui.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.label_1_1 = QtGui.QLabel(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1_1.sizePolicy().hasHeightForWidth())
        self.label_1_1.setSizePolicy(sizePolicy)
        self.label_1_1.setFrameShape(QtGui.QFrame.Box)
        self.label_1_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_1_1.setObjectName("label_1_1")
        self.horizontalLayout_1.addWidget(self.label_1_1)
        self.lineEdit_1 = QtGui.QLineEdit(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_1.setSizePolicy(sizePolicy)
        self.lineEdit_1.setReadOnly(True)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout_1.addWidget(self.lineEdit_1)
        self.label_1_2 = QtGui.QLabel(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1_2.sizePolicy().hasHeightForWidth())
        self.label_1_2.setSizePolicy(sizePolicy)
        self.label_1_2.setFrameShape(QtGui.QFrame.Box)
        self.label_1_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_1_2.setObjectName("label_1_2")
        self.horizontalLayout_1.addWidget(self.label_1_2)
        self.comboBox_1 = QtGui.QComboBox(self.tab_1)
        self.comboBox_1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_1.sizePolicy().hasHeightForWidth())
        self.comboBox_1.setSizePolicy(sizePolicy)
        self.comboBox_1.setFrame(True)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem(QtCore.QString())
        self.comboBox_1.addItem(QtCore.QString())
        self.comboBox_1.addItem(QtCore.QString())
        self.comboBox_1.addItem(QtCore.QString())
        self.comboBox_1.addItem(QtCore.QString())
        self.comboBox_1.addItem(QtCore.QString())
        self.comboBox_1.addItem(QtCore.QString())
        self.comboBox_1.addItem(QtCore.QString())
        self.comboBox_1.addItem(QtCore.QString())
        self.comboBox_1.addItem(QtCore.QString())
        self.horizontalLayout_1.addWidget(self.comboBox_1)
        self.label_1_3 = QtGui.QLabel(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1_3.sizePolicy().hasHeightForWidth())
        self.label_1_3.setSizePolicy(sizePolicy)
        self.label_1_3.setFrameShape(QtGui.QFrame.Box)
        self.label_1_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_1_3.setObjectName("label_1_3")
        self.horizontalLayout_1.addWidget(self.label_1_3)
        self.label_1_4 = QtGui.QLabel(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1_4.sizePolicy().hasHeightForWidth())
        self.label_1_4.setSizePolicy(sizePolicy)
        self.label_1_4.setFrameShape(QtGui.QFrame.Box)
        self.label_1_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_1_4.setObjectName("label_1_4")
        self.horizontalLayout_1.addWidget(self.label_1_4)
        self.pushButton_1_1 = QtGui.QPushButton(self.tab_1)
        self.pushButton_1_1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1_1.setSizePolicy(sizePolicy)
        self.pushButton_1_1.setAutoDefault(False)
        self.pushButton_1_1.setDefault(False)
        self.pushButton_1_1.setFlat(False)
        self.pushButton_1_1.setObjectName("pushButton_1_1")
        self.horizontalLayout_1.addWidget(self.pushButton_1_1)
        self.gridLayout.addLayout(self.horizontalLayout_1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen_Recent = QtGui.QMenu(self.menuFile)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuOpen_Recent.setIcon(icon2)
        self.menuOpen_Recent.setObjectName("menuOpen_Recent")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFind = QtGui.QMenu(self.menubar)
        self.menuFind.setObjectName("menuFind")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon3)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExpand_Tree = QtGui.QAction(MainWindow)
        self.actionExpand_Tree.setEnabled(False)
        self.actionExpand_Tree.setObjectName("actionExpand_Tree")
        self.actionCollapse_Tree = QtGui.QAction(MainWindow)
        self.actionCollapse_Tree.setEnabled(False)
        self.actionCollapse_Tree.setObjectName("actionCollapse_Tree")
        self.actionInput_JSON = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/input.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInput_JSON.setIcon(icon4)
        self.actionInput_JSON.setObjectName("actionInput_JSON")
        self.actionFind = QtGui.QAction(MainWindow)
        self.actionFind.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind.setIcon(icon5)
        self.actionFind.setObjectName("actionFind")
        self.actionFind_Next = QtGui.QAction(MainWindow)
        self.actionFind_Next.setEnabled(False)
        self.actionFind_Next.setObjectName("actionFind_Next")
        self.actionFind_Previous = QtGui.QAction(MainWindow)
        self.actionFind_Previous.setEnabled(False)
        self.actionFind_Previous.setObjectName("actionFind_Previous")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setEnabled(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/saveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon6)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionEmpty = QtGui.QAction(MainWindow)
        self.actionEmpty.setEnabled(False)
        self.actionEmpty.setObjectName("actionEmpty")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon7)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon8)
        self.actionNew.setObjectName("actionNew")
        self.actionReload = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReload.setIcon(icon9)
        self.actionReload.setObjectName("actionReload")
        self.actionClose = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon10)
        self.actionClose.setObjectName("actionClose")
        self.menuOpen_Recent.addAction(self.actionEmpty)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuOpen_Recent.menuAction())
        self.menuFile.addAction(self.actionInput_JSON)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionReload)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menuAbout.addAction(self.actionAbout)
        self.menuView.addAction(self.actionExpand_Tree)
        self.menuView.addAction(self.actionCollapse_Tree)
        self.menuFind.addAction(self.actionFind)
        self.menuFind.addAction(self.actionFind_Next)
        self.menuFind.addAction(self.actionFind_Previous)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFind.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL("triggered()"), MainWindow.choosefile)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.actionAbout_Qt, QtCore.SIGNAL("triggered()"), MainWindow.aboutqt)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL("triggered()"), MainWindow.about)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), MainWindow.get_file)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), MainWindow.lineEdit_0.clear)
        QtCore.QObject.connect(self.lineEdit_0, QtCore.SIGNAL("returnPressed()"), MainWindow.pushButton.click)
        QtCore.QObject.connect(self.actionExpand_Tree, QtCore.SIGNAL("triggered()"), MainWindow.setBranchCollExp)
        QtCore.QObject.connect(self.actionCollapse_Tree, QtCore.SIGNAL("triggered()"), MainWindow.setBranchCollExp)
        QtCore.QObject.connect(self.actionInput_JSON, QtCore.SIGNAL("triggered()"), MainWindow.input_json)
        QtCore.QObject.connect(self.actionFind, QtCore.SIGNAL("triggered()"), MainWindow.search_tree)
        QtCore.QObject.connect(self.actionFind_Next, QtCore.SIGNAL("triggered()"), MainWindow.find_next)
        QtCore.QObject.connect(self.actionFind_Previous, QtCore.SIGNAL("triggered()"), MainWindow.find_previous)
        QtCore.QObject.connect(self.treeWidget_1, QtCore.SIGNAL("currentItemChanged(QTreeWidgetItem *,QTreeWidgetItem *)"), MainWindow.printit)
        QtCore.QObject.connect(self.actionSave_As, QtCore.SIGNAL("triggered()"), MainWindow.saveAs)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL("currentChanged(int)"), MainWindow.onTabChanged)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL("triggered()"), MainWindow.save)
        QtCore.QObject.connect(self.pushButton_1_1, QtCore.SIGNAL("clicked()"), MainWindow.saveValue)
        QtCore.QObject.connect(self.textBrowser_1, QtCore.SIGNAL("undoAvailable(bool)"), self.pushButton_1_1.setEnabled)
        QtCore.QObject.connect(self.treeWidget_1, QtCore.SIGNAL("customContextMenuRequested(QPoint)"), MainWindow.showTreeContextMenu)
        QtCore.QObject.connect(self.actionNew, QtCore.SIGNAL("triggered()"), MainWindow.add_tab)
        QtCore.QObject.connect(self.actionReload, QtCore.SIGNAL("triggered()"), MainWindow.reload_tab)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), MainWindow.remove_tab)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pyJsonEditor", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_1.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1_1.setText(QtGui.QApplication.translate("MainWindow", "PATH:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1_2.setText(QtGui.QApplication.translate("MainWindow", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_1.setItemText(0, QtGui.QApplication.translate("MainWindow", "ordereddict", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_1.setItemText(1, QtGui.QApplication.translate("MainWindow", "list", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_1.setItemText(2, QtGui.QApplication.translate("MainWindow", "str", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_1.setItemText(3, QtGui.QApplication.translate("MainWindow", "unicode", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_1.setItemText(4, QtGui.QApplication.translate("MainWindow", "int", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_1.setItemText(5, QtGui.QApplication.translate("MainWindow", "long", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_1.setItemText(6, QtGui.QApplication.translate("MainWindow", "bool", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_1.setItemText(7, QtGui.QApplication.translate("MainWindow", "NoneType", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_1.setItemText(8, QtGui.QApplication.translate("MainWindow", "Decimal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_1.setItemText(9, QtGui.QApplication.translate("MainWindow", "undefined", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1_3.setText(QtGui.QApplication.translate("MainWindow", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1_4.setText(QtGui.QApplication.translate("MainWindow", "Encoding:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_1_1.setText(QtGui.QApplication.translate("MainWindow", "Save Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen_Recent.setTitle(QtGui.QApplication.translate("MainWindow", "Open Recent", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFind.setTitle(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setStatusTip(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setStatusTip(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExpand_Tree.setText(QtGui.QApplication.translate("MainWindow", "Expand Full Branch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExpand_Tree.setStatusTip(QtGui.QApplication.translate("MainWindow", "Expand Full Branch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExpand_Tree.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Right", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCollapse_Tree.setText(QtGui.QApplication.translate("MainWindow", "Collapse Full Branch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCollapse_Tree.setStatusTip(QtGui.QApplication.translate("MainWindow", "Collapse Full Branch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCollapse_Tree.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInput_JSON.setText(QtGui.QApplication.translate("MainWindow", "Input JSON...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInput_JSON.setStatusTip(QtGui.QApplication.translate("MainWindow", "Input JSON", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInput_JSON.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setText(QtGui.QApplication.translate("MainWindow", "Find...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setStatusTip(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Next.setText(QtGui.QApplication.translate("MainWindow", "Find Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Next.setStatusTip(QtGui.QApplication.translate("MainWindow", "Find Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Next.setShortcut(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Previous.setText(QtGui.QApplication.translate("MainWindow", "Find Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Previous.setStatusTip(QtGui.QApplication.translate("MainWindow", "Find Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Previous.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEmpty.setText(QtGui.QApplication.translate("MainWindow", "Empty", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setStatusTip(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload.setText(QtGui.QApplication.translate("MainWindow", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload.setStatusTip(QtGui.QApplication.translate("MainWindow", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setStatusTip(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))


