# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\weatherclientmain.ui'
#
# Created: Fri Dec 12 15:15:18 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WeatherClientMain(object):
    def setupUi(self, WeatherClientMain):
        WeatherClientMain.setObjectName(_fromUtf8("WeatherClientMain"))
        WeatherClientMain.resize(800, 600)
        self.centralwidget = QtGui.QWidget(WeatherClientMain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.leftTab = QtGui.QTabWidget(self.centralwidget)
        self.leftTab.setObjectName(_fromUtf8("leftTab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.inUUIDList = QtGui.QTableView(self.tab)
        self.inUUIDList.setSortingEnabled(False)
        self.inUUIDList.setObjectName(_fromUtf8("inUUIDList"))
        self.gridLayout.addWidget(self.inUUIDList, 4, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.inStartTime = QtGui.QDateTimeEdit(self.tab)
        self.inStartTime.setObjectName(_fromUtf8("inStartTime"))
        self.gridLayout.addWidget(self.inStartTime, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.inEndTime = QtGui.QDateTimeEdit(self.tab)
        self.inEndTime.setObjectName(_fromUtf8("inEndTime"))
        self.gridLayout.addWidget(self.inEndTime, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 5, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 5, 1, 1, 1)
        self.leftTab.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.cSMAPSource = QtGui.QGroupBox(self.tab_3)
        self.cSMAPSource.setObjectName(_fromUtf8("cSMAPSource"))
        self.gridLayout_6 = QtGui.QGridLayout(self.cSMAPSource)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.outSMAPHost = QtGui.QLineEdit(self.cSMAPSource)
        self.outSMAPHost.setEnabled(False)
        self.outSMAPHost.setObjectName(_fromUtf8("outSMAPHost"))
        self.gridLayout_6.addWidget(self.outSMAPHost, 0, 2, 1, 1)
        self.outSMAPPort = QtGui.QLineEdit(self.cSMAPSource)
        self.outSMAPPort.setEnabled(False)
        self.outSMAPPort.setObjectName(_fromUtf8("outSMAPPort"))
        self.gridLayout_6.addWidget(self.outSMAPPort, 0, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.cSMAPSource)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.cSMAPSource)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.cSMAPSource)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 3, 1, 1, 2)
        self.outSourceSize = QtGui.QLineEdit(self.cSMAPSource)
        self.outSourceSize.setEnabled(False)
        self.outSourceSize.setReadOnly(False)
        self.outSourceSize.setObjectName(_fromUtf8("outSourceSize"))
        self.gridLayout_6.addWidget(self.outSourceSize, 1, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.cSMAPSource)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.cSMAPSource, 2, 0, 1, 1)
        self.cSMAPServer = QtGui.QGroupBox(self.tab_3)
        self.cSMAPServer.setObjectName(_fromUtf8("cSMAPServer"))
        self.gridLayout_3 = QtGui.QGridLayout(self.cSMAPServer)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.cSMAPServer)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.outPort = QtGui.QLineEdit(self.cSMAPServer)
        self.outPort.setEnabled(False)
        self.outPort.setObjectName(_fromUtf8("outPort"))
        self.gridLayout_3.addWidget(self.outPort, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.cSMAPServer)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.outHost = QtGui.QLineEdit(self.cSMAPServer)
        self.outHost.setEnabled(False)
        self.outHost.setObjectName(_fromUtf8("outHost"))
        self.gridLayout_3.addWidget(self.outHost, 0, 1, 1, 1)
        self.outSMAPStatus = QtGui.QLabel(self.cSMAPServer)
        self.outSMAPStatus.setObjectName(_fromUtf8("outSMAPStatus"))
        self.gridLayout_3.addWidget(self.outSMAPStatus, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.cSMAPServer, 1, 0, 1, 1)
        self.inTestConnection = QtGui.QPushButton(self.tab_3)
        self.inTestConnection.setObjectName(_fromUtf8("inTestConnection"))
        self.gridLayout_5.addWidget(self.inTestConnection, 0, 0, 1, 1)
        self.leftTab.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.inCmdLine = QtGui.QLineEdit(self.tab_2)
        self.inCmdLine.setObjectName(_fromUtf8("inCmdLine"))
        self.gridLayout_4.addWidget(self.inCmdLine, 2, 0, 1, 3)
        self.inCmdSend_2 = QtGui.QPushButton(self.tab_2)
        self.inCmdSend_2.setObjectName(_fromUtf8("inCmdSend_2"))
        self.gridLayout_4.addWidget(self.inCmdSend_2, 2, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.inCmdSel = QtGui.QComboBox(self.tab_2)
        self.inCmdSel.setObjectName(_fromUtf8("inCmdSel"))
        self.inCmdSel.addItem(_fromUtf8(""))
        self.inCmdSel.addItem(_fromUtf8(""))
        self.inCmdSel.addItem(_fromUtf8(""))
        self.inCmdSel.addItem(_fromUtf8(""))
        self.inCmdSel.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.inCmdSel, 0, 1, 1, 3)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 3, 0, 1, 4)
        self.leftTab.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.leftTab, 0, 0, 1, 1)
        self.outLogBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.outLogBrowser.setObjectName(_fromUtf8("outLogBrowser"))
        self.gridLayout_2.addWidget(self.outLogBrowser, 1, 0, 1, 2)
        self.rightTab = QtGui.QTabWidget(self.centralwidget)
        self.rightTab.setMinimumSize(QtCore.QSize(388, 0))
        self.rightTab.setObjectName(_fromUtf8("rightTab"))
        self.gridLayout_2.addWidget(self.rightTab, 0, 1, 1, 1)
        WeatherClientMain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(WeatherClientMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuWeb_Portal = QtGui.QMenu(self.menubar)
        self.menuWeb_Portal.setObjectName(_fromUtf8("menuWeb_Portal"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        WeatherClientMain.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(WeatherClientMain)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        WeatherClientMain.setStatusBar(self.statusbar)
        self.actionConfig_Editor = QtGui.QAction(WeatherClientMain)
        self.actionConfig_Editor.setObjectName(_fromUtf8("actionConfig_Editor"))
        self.actionDatabase_Admin = QtGui.QAction(WeatherClientMain)
        self.actionDatabase_Admin.setObjectName(_fromUtf8("actionDatabase_Admin"))
        self.actionOpen_SMAP_Monitor = QtGui.QAction(WeatherClientMain)
        self.actionOpen_SMAP_Monitor.setObjectName(_fromUtf8("actionOpen_SMAP_Monitor"))
        self.actionOpen_SMAP_Plotter = QtGui.QAction(WeatherClientMain)
        self.actionOpen_SMAP_Plotter.setObjectName(_fromUtf8("actionOpen_SMAP_Plotter"))
        self.actionOpen_SMAP_Server = QtGui.QAction(WeatherClientMain)
        self.actionOpen_SMAP_Server.setObjectName(_fromUtf8("actionOpen_SMAP_Server"))
        self.actionTime_Series_DB = QtGui.QAction(WeatherClientMain)
        self.actionTime_Series_DB.setObjectName(_fromUtf8("actionTime_Series_DB"))
        self.actionSource_SSH_Client = QtGui.QAction(WeatherClientMain)
        self.actionSource_SSH_Client.setObjectName(_fromUtf8("actionSource_SSH_Client"))
        self.actionServer_SSH_Client = QtGui.QAction(WeatherClientMain)
        self.actionServer_SSH_Client.setObjectName(_fromUtf8("actionServer_SSH_Client"))
        self.actionSource_VNC = QtGui.QAction(WeatherClientMain)
        self.actionSource_VNC.setObjectName(_fromUtf8("actionSource_VNC"))
        self.menuTools.addAction(self.actionConfig_Editor)
        self.menuTools.addAction(self.actionDatabase_Admin)
        self.menuTools.addAction(self.actionTime_Series_DB)
        self.menuTools.addAction(self.actionSource_SSH_Client)
        self.menuTools.addAction(self.actionServer_SSH_Client)
        self.menuTools.addAction(self.actionSource_VNC)
        self.menuWeb_Portal.addAction(self.actionOpen_SMAP_Monitor)
        self.menuWeb_Portal.addSeparator()
        self.menuWeb_Portal.addAction(self.actionOpen_SMAP_Plotter)
        self.menuWeb_Portal.addAction(self.actionOpen_SMAP_Server)
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWeb_Portal.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(WeatherClientMain)
        self.leftTab.setCurrentIndex(1)
        self.rightTab.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(WeatherClientMain)

    def retranslateUi(self, WeatherClientMain):
        WeatherClientMain.setWindowTitle(_translate("WeatherClientMain", "BEST WeatherStation Client", None))
        self.label_6.setText(_translate("WeatherClientMain", "UUID", None))
        self.label_4.setText(_translate("WeatherClientMain", "Start", None))
        self.label_5.setText(_translate("WeatherClientMain", "End", None))
        self.label_3.setText(_translate("WeatherClientMain", "Loaded", None))
        self.pushButton.setText(_translate("WeatherClientMain", "Reload", None))
        self.pushButton_2.setText(_translate("WeatherClientMain", "Clear Selection", None))
        self.leftTab.setTabText(self.leftTab.indexOf(self.tab), _translate("WeatherClientMain", "UUID", None))
        self.cSMAPSource.setTitle(_translate("WeatherClientMain", "SMAP Source", None))
        self.outSMAPHost.setText(_translate("WeatherClientMain", "192.168.1.140", None))
        self.outSMAPPort.setText(_translate("WeatherClientMain", "8079", None))
        self.label_10.setText(_translate("WeatherClientMain", "Port", None))
        self.label_9.setText(_translate("WeatherClientMain", "IP", None))
        self.label_11.setText(_translate("WeatherClientMain", "Status Unknown", None))
        self.outSourceSize.setText(_translate("WeatherClientMain", "2.3", None))
        self.label_12.setText(_translate("WeatherClientMain", "Size", None))
        self.cSMAPServer.setTitle(_translate("WeatherClientMain", "SMAP Server", None))
        self.label.setText(_translate("WeatherClientMain", "IP", None))
        self.outPort.setText(_translate("WeatherClientMain", "8080", None))
        self.label_2.setText(_translate("WeatherClientMain", "Port", None))
        self.outHost.setText(_translate("WeatherClientMain", "192.168.1.108", None))
        self.outSMAPStatus.setText(_translate("WeatherClientMain", "Status Unknown", None))
        self.inTestConnection.setText(_translate("WeatherClientMain", "Test Connection", None))
        self.leftTab.setTabText(self.leftTab.indexOf(self.tab_3), _translate("WeatherClientMain", "SMAPStatus", None))
        self.inCmdSend_2.setText(_translate("WeatherClientMain", "Send", None))
        self.label_8.setText(_translate("WeatherClientMain", "Command", None))
        self.inCmdSel.setItemText(0, _translate("WeatherClientMain", "Power Reset", None))
        self.inCmdSel.setItemText(1, _translate("WeatherClientMain", "Download Raw Data", None))
        self.inCmdSel.setItemText(2, _translate("WeatherClientMain", "Get System Status", None))
        self.inCmdSel.setItemText(3, _translate("WeatherClientMain", "Update System Config", None))
        self.inCmdSel.setItemText(4, _translate("WeatherClientMain", "New Item", None))
        self.label_7.setText(_translate("WeatherClientMain", "Command Idle", None))
        self.leftTab.setTabText(self.leftTab.indexOf(self.tab_2), _translate("WeatherClientMain", "SMAPControl", None))
        self.menuTools.setTitle(_translate("WeatherClientMain", "Tools", None))
        self.menuWeb_Portal.setTitle(_translate("WeatherClientMain", "Web Portal", None))
        self.menuHelp.setTitle(_translate("WeatherClientMain", "Help", None))
        self.actionConfig_Editor.setText(_translate("WeatherClientMain", "Config Editor", None))
        self.actionDatabase_Admin.setText(_translate("WeatherClientMain", "Database Admin", None))
        self.actionOpen_SMAP_Monitor.setText(_translate("WeatherClientMain", "Open SMAP Monitor", None))
        self.actionOpen_SMAP_Plotter.setText(_translate("WeatherClientMain", "Open SMAP Plotter", None))
        self.actionOpen_SMAP_Server.setText(_translate("WeatherClientMain", "Open SMAP Server", None))
        self.actionTime_Series_DB.setText(_translate("WeatherClientMain", "Time Series DB", None))
        self.actionSource_SSH_Client.setText(_translate("WeatherClientMain", "Source SSH Client", None))
        self.actionServer_SSH_Client.setText(_translate("WeatherClientMain", "Server SSH Client", None))
        self.actionSource_VNC.setText(_translate("WeatherClientMain", "Source VNC", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    WeatherClientMain = QtGui.QMainWindow()
    ui = Ui_WeatherClientMain()
    ui.setupUi(WeatherClientMain)
    WeatherClientMain.show()
    sys.exit(app.exec_())

